### PR TITLE
BKRCast customization dll

### PR DESCRIPTION
**Pull request by dong-bellevue**
City of Bellevue staff created daysim customization for BKRCast. This bkr.dll incorporates all customization created in SoundCast (psrc.dll), and creates new code and coefficients to better fit BKR conditions.

### CODE REVIEW

**Comment by bstabler** [comment]
Thanks @dong-bellevue.  Once we get your latest model setup into the test system, we'll be able to confirm this DLL also works for your model.  Stay tuned.

**Comment by bstabler** [comment]
FYI @dong-bellevue, the `DaySim.Customizations/BKR/ChoiceModels/H/Models/BKR_WorkLocationModel.cs` is not needed since the H version of the models is not used.  We'll go ahead and leave it in rather than have you revise.

**Comment by dong-bellevue** [comment]
@bstabler does it mean I can remove everything I created in H model folder? Is H model deprecated or will be used in the future? Thanks.

**Comment by dong-bellevue** [comment]
> FYI @dong-bellevue, the DaySim.Customizations/BKR/ChoiceModels/H/Models/BKR_WorkLocationModel.cs is not needed since the H version of the models is not used.  We'll go ahead and leave it in rather than have you revise.

@bstabler does it mean I can remove everything I created in H model folder? Is H model deprecated or will be used in the future? Thanks.

**Comment by bstabler** [comment]
yes, deprecated

**Comment by blakerosenthal** [comment]
@dong-bellevue @bstabler This PR has been squashed and merged to develop (https://github.com/RSGInc/DaySim/commit/2ccd37527b649570d62d4af6065cbbc5fbc6a55d)! Thank you :)

**Pull request closed without merging**
